### ISSUE TITLE
Spring config

### ISSUE THREAD

**Issue by raphsoft** [rajithd/spring-boot-oauth2#1]
Have you tried to use spring config in your project? Everytime I tried, I was not able to retrieve configuration from config files (properties) or config server using @Value annotation. I'm not sure if it's a conflict or anything. Do you have any idea?

**Comment by rajithd** [comment]
Is it a spring-boot project ? If so you can use application.properties file to hold configuration (@Value). If not you have to configure your property source. Better if you can post your spring config.

**Comment by gariem** [comment]
Hey, can you please close this issue? I realized that the problem was originated by the MyBatis @MapperScan annotation, which is instantiated before the properties place holder.
