### ISSUE TITLE
Missing grant type

### ISSUE THREAD

**Issue by ppavan895** [rajithd/spring-boot-oauth2#15]
Hi,

I am getting below error while giving curl cmd ..
.curl -vu rajithapp:secret 'http://localhost:9191/api/oauth/token
username=admin&password=admin&grant_type=password'

INFO 7804 --- [nio-9191-exec-4] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidRequestException, Missing grant type

  
![error](https://user-images.githubusercontent.com/29632486/27470665-aca4b078-5812-11e7-91fc-2fd94e548da5.png)

please help me.

**Comment by manojci** [comment]
@ppavan895 use double quotes. it should work
curl -vu rajithapp:secret "http://localhost:9191/api/oauth/token
username=admin&password=admin&grant_type=password"

**Comment by ppavan895** [comment]
Thanks Manojci .... its working
